### ISSUE TITLE
Why does upsert do SELECT before INSERT?

### ISSUE THREAD

**Issue by smallnamespace** [gajus/slonik-utilities#12]
The `INSERT ON CONFLICT ...` should leave the database in the same state as before if the SELECT clause would have returned no rows. Is there any reason to break upsert into two phases?

**Comment by gajus** [comment]
(Closing this since it's a question, not an issue, but please continue discussion.)

I've designed these utilities at the time when I was dealing with scaling challenges of a system where 90%+ of these upsert calls were always satisfied by `SELECT`, and while I don't distinctly remember the reason, it was either locking or observable performance issue that I was able to resolve using this pattern.

In order to re-evaluate this, I would need a reference showing that the locking implication / performance is the same.
